services:
  - type: web
    name: flask-web-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: SECRET_KEY
        sync: false
